[tool.poetry]
name = "mlops-neechev"
version = "0.1.0"
description = ""
authors = ["Fakazuma <me@example.com>"]
readme = "README.md"

packages = [
    {include = "resnet" }
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.25"
#torch = [
#  {url = "https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp39-cp39-win_amd64.whl"},
#]
#torchvision = [
#  {url = "https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp39-cp39-win_amd64.whl"},
#]
click = "^8.1.7"
timm = "^0.9.7"

[tool.poetry.group.dev.dependencies]
setuptools = "^68.2.2"
pre-commit = "^3.4.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
