hydra/job_logging: disabled
hydra/hydra_logging: disabled

defaults:
    - _self_

experiment_name: "Experiment"

model: microsoft/resnet-18

optimizer:
    lr: 0.01

data:
    data_dir: "./data"
    val_part: 0.2
    batch_size: 64
    dataloader_num_workers: 8

trainer:
    root_log_dir: "."
    max_epochs: 3

test:
    weights_path: "checkpoints/mnist-checkpoint.ckpt"

checkpoint:
    savedir: "./checkpoints"

logger:
    uri: "http://127.0.0.1:8085"
