hydra/job_logging: disabled
hydra/hydra_logging: disabled

defaults:
    - _self_

model: microsoft/resnet-18

optimizer:
    lr: 0.01

data:
    data_dir: "./data"
    val_part: 0.2
    batch_size: 64
    dataloader_num_workers: 8


trainer:
    root_log_dir: "."
    max_epochs: 1

test:
    weights_path: 'lightning_logs/version_13/checkpoints/epoch=1-step=750.ckpt'